package greenpasteures.reports;

import java.io.FileWriter;
import java.time.LocalDate;
import java.util.ArrayList;

public class CSVExporter {

    private FarmReport report;

    
    public CSVExporter(FarmReport report) {
        this.report = report;
    }

    //method to export the report to CSV 
    public void exportToCSV(String folderPath) {
        String fileName = folderPath + "/FarmStatusReport_" + LocalDate.now() + ".csv";

        try {
            FileWriter writer = new FileWriter(fileName);

            writer.write("GREEN PASTURES FARM - FARM STATUS REPORT\n");
            writer.write("Generated By:," + report.getGeneratedBy() + "\n");
            writer.write("Generated On:," + report.getGeneratedDate() + "\n");
            writer.write("\n");

            writer.write("LIVESTOCK SUMMARY\n");
            writer.write("Total Animals:," + report.getTotalAnimals() + "\n");
            writer.write("Cattle:," + report.getCattleList().size() + "\n");
            writer.write("Sheep:," + report.getSheepList().size() + "\n");
            writer.write("Poultry:," + report.getPoultryList().size() + "\n");
            writer.write("\n");

            writer.write("STATUS BREAKDOWN\n");
            writer.write("Healthy:,"  + report.getTotalHealthy() + "\n");
            writer.write("Sick:,"     + report.getTotalSick() + "\n");
            writer.write("Sold:,"     + report.getTotalSold() + "\n");
            writer.write("Deceased:," + report.getTotalDead() + "\n");
            writer.write("Lost:,"     + report.getTotalLost() + "\n");
            writer.write("Stolen:,"   + report.getTotalStolen() + "\n");
            writer.write("\n");

            
            writer.write("CATTLE\n");
            writer.write("Tag Number,Breed,Gender,Status,Date Registered,Purpose,Milk Collected (L),Weight (kg)\n");
            ArrayList<String[]> cattleList = report.getCattleList();
            for (int i = 0; i < cattleList.size(); i++) {
                String[] row = cattleList.get(i);
                writer.write(row[0] + "," + row[1] + "," + row[2] + "," + row[3] + "," + row[4] + "," + row[5] + "," + row[6] + "," + row[7] + "\n");
            }
            writer.write("\n");

            
            writer.write("SHEEP\n");
            writer.write("Tag Number,Breed,Gender,Status,Date Registered,Wool (kg),Is Breeder\n");
            ArrayList<String[]> sheepList = report.getSheepList();
            for (int i = 0; i < sheepList.size(); i++) {
                String[] row = sheepList.get(i);
                writer.write(row[0] + "," + row[1] + "," + row[2] + "," + row[3] + "," + row[4] + "," + row[5] + "," + row[6] + "\n");
            }
            writer.write("\n");

            
            writer.write("POULTRY\n");
            writer.write("Tag Number,Breed,Gender,Status,Date Registered,Type,Eggs Collected,Housing Unit\n");
            ArrayList<String[]> poultryList = report.getPoultryList();
            for (int i = 0; i < poultryList.size(); i++) {
                String[] row = poultryList.get(i);
                writer.write(row[0] + "," + row[1] + "," + row[2] + "," + row[3] + "," + row[4] + "," + row[5] + "," + row[6] + "," + row[7] + "\n");
            }
            writer.write("\n");

           
            writer.write("STOCK ITEMS\n");
            writer.write("Item ID,Name,Category,Quantity,Unit,Reorder Level,Last Updated\n");
            ArrayList<String[]> stockList = report.getStockList();
            for (int i = 0; i < stockList.size(); i++) {
                String[] row = stockList.get(i);
                writer.write(row[0] + "," + row[1] + "," + row[2] + "," + row[3] + "," + row[4] + "," + row[5] + "," + row[6] + "\n");
            }
            writer.write("\n");

            
            writer.write("HEALTH RECORDS\n");
            writer.write("Record ID,Tag Number,Treatment Date,Diagnosis,Treatment,Medicine Used,Attended By\n");
            ArrayList<String[]> healthList = report.getHealthRecordList();
            for (int i = 0; i < healthList.size(); i++) {
                String[] row = healthList.get(i);
                writer.write(row[0] + "," + row[1] + "," + row[2] + "," + row[3] + "," + row[4] + "," + row[5] + "," + row[6] + "\n");
            }

            writer.close();
            System.out.println("CSV file saved to: " + fileName);

        } catch (Exception e) {
            System.out.println("Error saving CSV file: " + e.getMessage());
        }
    }
}