package greenpasteures.reports;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.util.ArrayList;

public class PDFExporter {

    private FarmReport report;

   
    private Font titleFont;
    private Font headingFont;
    private Font boldFont;
    private Font normalFont;

   
    private BaseColor darkGreen;
    private BaseColor lightGreen;

    
    public PDFExporter(FarmReport report) {
        this.report = report;

        titleFont   = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD,   BaseColor.WHITE);
        headingFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD,   BaseColor.WHITE);
        boldFont    = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD);
        normalFont  = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL);

        darkGreen  = new BaseColor(34, 85, 34);
        lightGreen = new BaseColor(144, 199, 144);
    }

    //method to exports the report to PDF
    public void exportToPDF(String folderPath) {
        String fileName = folderPath + "/FarmStatusReport_" + LocalDate.now() + ".pdf";
        Document document = new Document(PageSize.A4, 36, 36, 54, 36);

        try {
            PdfWriter.getInstance(document, new FileOutputStream(fileName));
            document.open();

            addTitleSection(document);
            addSummarySection(document);
            addCattleSection(document);
            addSheepSection(document);
            addPoultrySection(document);
            addStockSection(document);
            addHealthRecordsSection(document);

            document.close();
            System.out.println("PDF file saved to: " + fileName);

        } catch (Exception e) {
            System.out.println("Error saving PDF file: " + e.getMessage());
        }
    }

    //adding title at the top of the PDF
    private void addTitleSection(Document document) throws Exception {
        PdfPTable titleTable = new PdfPTable(1);
        titleTable.setWidthPercentage(100);

        PdfPCell titleCell = new PdfPCell(new Phrase("GREEN PASTURES FARM", titleFont));
        titleCell.setBackgroundColor(darkGreen);
        titleCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        titleCell.setPadding(12);
        titleTable.addCell(titleCell);

        PdfPCell subCell = new PdfPCell(new Phrase("Farm Status Report", boldFont));
        subCell.setBackgroundColor(lightGreen);
        subCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        subCell.setPadding(6);
        titleTable.addCell(subCell);

        document.add(titleTable);
        document.add(new Paragraph(" "));
        document.add(new Paragraph("Generated By: " + report.getGeneratedBy(), boldFont));
        document.add(new Paragraph("Generated On: " + report.getGeneratedDate(), boldFont));
        document.add(new Paragraph(" "));
    }

    //adding summary section
    private void addSummarySection(Document document) throws Exception {
        document.add(makeSectionHeading("LIVESTOCK SUMMARY"));

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(50);
        table.setHorizontalAlignment(Element.ALIGN_LEFT);

        addTableRow(table, "Total Animals",  String.valueOf(report.getTotalAnimals()));
        addTableRow(table, "Cattle",         String.valueOf(report.getCattleList().size()));
        addTableRow(table, "Sheep",          String.valueOf(report.getSheepList().size()));
        addTableRow(table, "Poultry",        String.valueOf(report.getPoultryList().size()));
        addTableRow(table, "Healthy",        String.valueOf(report.getTotalHealthy()));
        addTableRow(table, "Sick",           String.valueOf(report.getTotalSick()));
        addTableRow(table, "Sold",           String.valueOf(report.getTotalSold()));
        addTableRow(table, "Deceased",       String.valueOf(report.getTotalDead()));
        addTableRow(table, "Lost",           String.valueOf(report.getTotalLost()));
        addTableRow(table, "Stolen",         String.valueOf(report.getTotalStolen()));

        document.add(table);
        document.add(new Paragraph(" "));
    }

    
    private void addCattleSection(Document document) throws Exception {
        document.add(makeSectionHeading("CATTLE"));
        String[] headers = {"Tag No", "Breed", "Gender", "Status", "Registered", "Purpose", "Milk (L)", "Weight (kg)"};
        document.add(makeDataTable(headers, report.getCattleList()));
        document.add(new Paragraph(" "));
    }

    
    private void addSheepSection(Document document) throws Exception {
        document.add(makeSectionHeading("SHEEP"));
        String[] headers = {"Tag No", "Breed", "Gender", "Status", "Registered", "Wool (kg)", "Breeder"};
        document.add(makeDataTable(headers, report.getSheepList()));
        document.add(new Paragraph(" "));
    }

    
    private void addPoultrySection(Document document) throws Exception {
        document.add(makeSectionHeading("POULTRY"));
        String[] headers = {"Tag No", "Breed", "Gender", "Status", "Registered", "Type", "Eggs", "Housing"};
        document.add(makeDataTable(headers, report.getPoultryList()));
        document.add(new Paragraph(" "));
    }

    
    private void addStockSection(Document document) throws Exception {
        document.add(makeSectionHeading("STOCK ITEMS"));
        String[] headers = {"ID", "Name", "Category", "Quantity", "Unit", "Reorder Level", "Last Updated"};
        document.add(makeDataTable(headers, report.getStockList()));
        document.add(new Paragraph(" "));
    }

    
    private void addHealthRecordsSection(Document document) throws Exception {
        document.add(makeSectionHeading("HEALTH RECORDS"));
        String[] headers = {"ID", "Tag No", "Date", "Diagnosis", "Treatment", "Medicine", "Attended By"};
        document.add(makeDataTable(headers, report.getHealthRecordList()));
    }

    
    private PdfPTable makeSectionHeading(String title) throws Exception {
        PdfPTable headingTable = new PdfPTable(1);
        headingTable.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell(new Phrase(title, headingFont));
        cell.setBackgroundColor(darkGreen);
        cell.setPadding(6);
        headingTable.addCell(cell);
        return headingTable;
    }

    //method to create a data table with headers and rows
    private PdfPTable makeDataTable(String[] headers, ArrayList<String[]> rows) throws Exception {
        PdfPTable table = new PdfPTable(headers.length);
        table.setWidthPercentage(100);

        for (int i = 0; i < headers.length; i++) {
            PdfPCell cell = new PdfPCell(new Phrase(headers[i], boldFont));
            cell.setBackgroundColor(lightGreen);
            cell.setPadding(5);
            table.addCell(cell);
        }

        for (int i = 0; i < rows.size(); i++) {
            String[] row = rows.get(i);
            for (int j = 0; j < row.length; j++) {
                PdfPCell cell = new PdfPCell(new Phrase(row[j] != null ? row[j] : "-", normalFont));
                cell.setPadding(4);
                table.addCell(cell);
            }
        }

        if (rows.size() == 0) {
            PdfPCell emptyCell = new PdfPCell(new Phrase("No records found.", normalFont));
            emptyCell.setColspan(headers.length);
            emptyCell.setPadding(5);
            table.addCell(emptyCell);
        }

        return table;
    }

    
    private void addTableRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, boldFont));
        PdfPCell valueCell = new PdfPCell(new Phrase(value, normalFont));
        labelCell.setPadding(5);
        valueCell.setPadding(5);
        table.addCell(labelCell);
        table.addCell(valueCell);
    }
}